defaults:
  - task: square_image_abs

name: train_dp_teacher

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "debug"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True
past_action_visible: False

policy:
  _target_: diffusion_policy_3d.policy.DP_Teacher.DP_Teacher
  # use_point_crop: true
  condition_type: film
  use_down_condition: true
  use_mid_condition: true
  use_up_condition: true
  
  diffusion_step_embed_dim: 128
  # down_dims: [256,512,1024]
  down_dims:
  - 512
  - 1024
  - 2048

  # crop_shape: [76,76]
  # encoder_output_dim: 64
  horizon: ${horizon}
  kernel_size: 5
  n_action_steps: ${n_action_steps}
  n_groups: 8
  n_obs_steps: ${n_obs_steps}

  obs_encoder:
    _target_: diffusion_policy_3d.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: diffusion_policy_3d.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: [76, 76]
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: False

  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: sample

  scheduler:
    _target_: diffusers.schedulers.scheduling_lcm.LCMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: sample

  num_inference_timesteps: 1 # The inference steps of ManiCM.
  num_inference_steps: 10 # DDIM steps
  obs_as_global_cond: true
  shape_meta: ${shape_meta}


ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 2048 #128
  num_workers: 20 #64
  shuffle: True
  pin_memory: True
  persistent_workers: True #False

val_dataloader:
  batch_size: 2048 #128
  num_workers: 20 #64
  shuffle: False
  pin_memory: True
  persistent_workers: True #False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 1000 #3000
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 50 #50 #200
  checkpoint_every: 50 #50 #200
  val_every: 50 #1
  sample_every: 50 #5
  val_sample_every: 50
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

output_dir: /mnt/home/SongJiaqi/Documents/ManiCM/ManiCM/outputs/dp_teacher/square-large #outputs/dp_teacher/square

logging:
  group: ${exp_name}
  id: null
  mode: offline
  name: DPTeacher-bz4096-dim2048 # ${exp_name}
  project: ManiCM-DPTeacher
  resume: False
  tags:
  - manicm 
  - robomimic

checkpoint:
  save_ckpt: False #True # if True, save checkpoint every checkpoint_every
  topk:
    monitor_key: val_mse_error # test_mean_score
    mode: min #max
    k: 8 #1
    format_str: 'epoch={epoch:04d}-val_mse_error={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True # this only saves when save_ckpt is True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}